# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyWindowClass.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 488)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(850, 430, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 781, 451))
        self.tabWidget.setStyleSheet("background-color: rgb(235, 235, 235);")
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(420, 20, 351, 271))
        font = QtGui.QFont()
        font.setFamily("Ayuthaya")
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.imgWidgetShow = QtWidgets.QLabel(self.groupBox)
        self.imgWidgetShow.setGeometry(QtCore.QRect(10, 40, 320, 220))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.imgWidgetShow.setFont(font)
        self.imgWidgetShow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.imgWidgetShow.setStyleSheet("background-color: rgb(191, 191, 191);")
        self.imgWidgetShow.setAlignment(QtCore.Qt.AlignCenter)
        self.imgWidgetShow.setWordWrap(False)
        self.imgWidgetShow.setIndent(-6)
        self.imgWidgetShow.setObjectName("imgWidgetShow")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(11, 20, 400, 271))
        font = QtGui.QFont()
        font.setFamily("Ayuthaya")
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(160, 30, 241, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ayuthaya")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.line_name = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_name.setObjectName("line_name")
        self.gridLayout.addWidget(self.line_name, 2, 1, 1, 1)
        self.line_num = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_num.setObjectName("line_num")
        self.gridLayout.addWidget(self.line_num, 1, 1, 1, 1)
        self.line_position = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_position.setObjectName("line_position")
        self.gridLayout.addWidget(self.line_position, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ayuthaya")
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.line_card = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_card.setObjectName("line_card")
        self.gridLayout.addWidget(self.line_card, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ayuthaya")
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ayuthaya")
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.line_lname = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_lname.setObjectName("line_lname")
        self.gridLayout.addWidget(self.line_lname, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Ayuthaya")
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.line_under = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_under.setObjectName("line_under")
        self.gridLayout.addWidget(self.line_under, 5, 1, 1, 1)
        self.img_person = QtWidgets.QLabel(self.groupBox_2)
        self.img_person.setGeometry(QtCore.QRect(10, 30, 131, 131))
        self.img_person.setStyleSheet("\n"
"background-color: rgb(191, 191, 191);")
        self.img_person.setAlignment(QtCore.Qt.AlignCenter)
        self.img_person.setObjectName("img_person")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 300, 771, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_3)
        self.progressBar.setGeometry(QtCore.QRect(20, 50, 730, 21))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.groupBox.setTitle(_translate("MainWindow", "Camera"))
        self.imgWidgetShow.setText(_translate("MainWindow", "Loading Camera..."))
        self.groupBox_2.setTitle(_translate("MainWindow", "ข้อมูลพนักงาน"))
        self.label_3.setText(_translate("MainWindow", "เลขประจำตัว:"))
        self.label_6.setText(_translate("MainWindow", "ตำแหน่ง:"))
        self.label_2.setText(_translate("MainWindow", "Card No:"))
        self.label_4.setText(_translate("MainWindow", "ชื่อ:"))
        self.label_5.setText(_translate("MainWindow", "นามสกุล:"))
        self.label_7.setText(_translate("MainWindow", "สังกัด:"))
        self.img_person.setText(_translate("MainWindow", "personalImage"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "หน้าหลัก"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

